/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IClaimIssuer__factory } from "./IClaimIssuer__factory";
export { IERC734__factory } from "./IERC734__factory";
export { IERC735__factory } from "./IERC735__factory";
export { IIdentity__factory } from "./IIdentity__factory";
export { IImplementationAuthority__factory } from "./IImplementationAuthority__factory";
