[profile.default]
src = "contracts"
out = "out"
test = "test"
libs = ["dependencies"]

solc_version = "0.8.27"
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"

[profile.default.fmt]
sort_imports = true
contract_new_lines = true
bracket_spacing = true

[soldeer]
remappings_regenerate = false

[dependencies]
forge-std = "1.11.0"
"@openzeppelin-contracts" = "5.2.0"
"@openzeppelin-contracts-upgradeable" = "4.9.6"
solady = "0.1.15"
