/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IdentityProxy } from "./IdentityProxy";
export type { ImplementationAuthority } from "./ImplementationAuthority";
