/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IImplementationAuthorityInterface extends utils.Interface {
  functions: {
    "getImplementation()": FunctionFragment;
    "updateImplementation(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getImplementation" | "updateImplementation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateImplementation",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateImplementation",
    data: BytesLike
  ): Result;

  events: {
    "UpdatedImplementation(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "UpdatedImplementation"): EventFragment;
}

export interface UpdatedImplementationEventObject {
  newAddress: string;
}
export type UpdatedImplementationEvent = TypedEvent<
  [string],
  UpdatedImplementationEventObject
>;

export type UpdatedImplementationEventFilter =
  TypedEventFilter<UpdatedImplementationEvent>;

export interface IImplementationAuthority extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IImplementationAuthorityInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getImplementation(overrides?: CallOverrides): Promise<[string]>;

    updateImplementation(
      _newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getImplementation(overrides?: CallOverrides): Promise<string>;

  updateImplementation(
    _newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getImplementation(overrides?: CallOverrides): Promise<string>;

    updateImplementation(
      _newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "UpdatedImplementation(address)"(
      newAddress?: null
    ): UpdatedImplementationEventFilter;
    UpdatedImplementation(newAddress?: null): UpdatedImplementationEventFilter;
  };

  estimateGas: {
    getImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    updateImplementation(
      _newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getImplementation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateImplementation(
      _newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
