/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IClaimIssuer } from "./IClaimIssuer";
export type { IERC734 } from "./IERC734";
export type { IERC735 } from "./IERC735";
export type { IIdentity } from "./IIdentity";
export type { IImplementationAuthority } from "./IImplementationAuthority";
