/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IIdFactory__factory } from "./IIdFactory__factory";
export { IdFactory__factory } from "./IdFactory__factory";
