name: Unit tests workflow
on: push

jobs:

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    container: node:12

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@tokenyico'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_FOR_GPR}}
      - name: Lint sources
        run:
          npm run lint


  test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    container: node:12

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@tokenyico'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_FOR_GPR}}
      - name: Build application
        run: npm run build
      - name: Run tests
        run: npm run test
